"""
main.py
Orchestrates the 3-Agent AutoML pipeline.

Usage:
  python main.py                          # uses default sample data
  python main.py --csv path/to/data.csv --target ColumnName
"""

import argparse
import os
import time
import pandas as pd
from datetime import datetime

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(__file__)
DATA_DIR   = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
LOG_DIR    = os.path.join(BASE_DIR, "logs")

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

# ── Agents ────────────────────────────────────────────────────────────────────
from agents.agent1_cleaner  import run_agent1
from agents.agent2_engineer import run_agent2
from agents.agent3_trainer  import run_agent3


def generate_final_report(
    raw_csv: str,
    target: str,
    agent1_summary: str,
    agent2_summary: str,
    final_metrics: dict,
    log_lines: list,
    duration_seconds: float,
) -> str:
    """Produces a Markdown report summarizing the whole pipeline run."""

    raw_df = pd.read_csv(raw_csv)
    clean_path = os.path.join(OUTPUT_DIR, "clean_data.csv")
    eng_path   = os.path.join(OUTPUT_DIR, "engineered_data.csv")

    clean_shape = pd.read_csv(clean_path).shape if os.path.exists(clean_path) else ("?", "?")
    eng_shape   = pd.read_csv(eng_path).shape   if os.path.exists(eng_path)   else ("?", "?")

    acc  = final_metrics.get("accuracy",  "N/A")
    f1   = final_metrics.get("f1",        "N/A")
    rec  = final_metrics.get("recall",    "N/A")
    iters = final_metrics.get("iterations", "N/A")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""# AutoML Team — Final Report
Generated: {timestamp}

---

## Dataset Summary

| Stage          | Rows | Columns |
|----------------|------|---------|
| Raw input      | {raw_df.shape[0]}   | {raw_df.shape[1]}      |
| After cleaning | {clean_shape[0]}   | {clean_shape[1]}      |
| After engineering | {eng_shape[0]}   | {eng_shape[1]}      |

**Target column:** `{target}`

---

## Agent 1 — Data Cleaner ("The Auditor")

{agent1_summary if agent1_summary else "_No summary captured._"}

---

## Agent 2 — Feature Engineer ("The Architect")

{agent2_summary if agent2_summary else "_No summary captured._"}

---

## Agent 3 — Model Trainer ("The Coder")

| Metric   | Score |
|----------|-------|
| Accuracy | {acc if isinstance(acc, str) else f"{acc:.4f}"} |
| F1 Score | {f1 if isinstance(f1, str) else f"{f1:.4f}"} |
| Recall   | {rec if isinstance(rec, str) else f"{rec:.4f}"} |

**Training iterations:** {iters}

{final_metrics.get("report", "")}

---

## Pipeline Execution

- **Total runtime:** {duration_seconds:.1f} seconds
- **Clean data saved to:** `outputs/clean_data.csv`
- **Engineered data saved to:** `outputs/engineered_data.csv`
- **Best model code saved to:** `outputs/best_model_code.py`
- **Full log saved to:** `logs/run.log`

---

*Generated by the Multi-Agent AutoML Team*
"""
    return report


def main():
    parser = argparse.ArgumentParser(description="Multi-Agent AutoML Pipeline")
    parser.add_argument("--csv",    default=os.path.join(DATA_DIR, "sample_data.csv"),
                        help="Path to raw CSV file")
    parser.add_argument("--target", default="Survived",
                        help="Target column name to predict")
    args = parser.parse_args()

    log_lines = []
    start_time = time.time()

    print("\n" + "★"*60)
    print("  MULTI-AGENT AUTOML TEAM — STARTING PIPELINE")
    print("★"*60)
    print(f"  Input:  {args.csv}")
    print(f"  Target: {args.target}")
    print("★"*60 + "\n")

    # ── Agent 1 ───────────────────────────────────────────────────────────────
    clean_path, agent1_summary = run_agent1(
        raw_csv_path=args.csv,
        output_dir=OUTPUT_DIR,
        log_lines=log_lines,
    )

    # ── Agent 2 ───────────────────────────────────────────────────────────────
    eng_path, agent2_summary = run_agent2(
        clean_csv_path=clean_path,
        agent1_summary=agent1_summary,
        target_column=args.target,
        output_dir=OUTPUT_DIR,
        log_lines=log_lines,
    )

    # ── Agent 3 ───────────────────────────────────────────────────────────────
    final_metrics = run_agent3(
        engineered_csv_path=eng_path,
        agent1_summary=agent1_summary,
        agent2_summary=agent2_summary,
        target_column=args.target,
        output_dir=OUTPUT_DIR,
        log_lines=log_lines,
    )

    duration = time.time() - start_time

    # ── Final Report ──────────────────────────────────────────────────────────
    report_md = generate_final_report(
        raw_csv=args.csv,
        target=args.target,
        agent1_summary=agent1_summary,
        agent2_summary=agent2_summary,
        final_metrics=final_metrics,
        log_lines=log_lines,
        duration_seconds=duration,
    )

    report_path = os.path.join(OUTPUT_DIR, "final_report.md")
    with open(report_path, "w") as f:
        f.write(report_md)

    log_path = os.path.join(LOG_DIR, "run.log")
    with open(log_path, "w") as f:
        f.write("\n".join(log_lines))

    print("\n" + "★"*60)
    print("  PIPELINE COMPLETE")
    print("★"*60)
    print(f"  Final report: {report_path}")
    print(f"  Execution log: {log_path}")
    acc = final_metrics.get("accuracy", "N/A")
    print(f"  Final accuracy: {acc if isinstance(acc, str) else f'{acc:.4f}'}")
    print("★"*60 + "\n")


if __name__ == "__main__":
    main()